web-3/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Home
Route::get('/', 'RecipeController@home')->name('home');

// Recipes
Route::resource('recipes', 'RecipeController');

Auth::routes();

// All those that require authentication.
Route::middleware(['auth'])->group(function() {
    Route::get('profile/{id}/edit', 'ProfileController@edit')->name('profile.edit');
    Route::put('profile/{id}/update', 'ProfileController@update')->name('profile.update');
    Route::get('profile/{id}/generate-token', 'ProfileController@generateToken')->name('profile.generate');
    Route::get('users/export/export-all', 'UserController@export_users')->name('user.export');
    Route::get('users/export', 'UserController@export')->name('export');
    Route::get('admin', 'AdminController@index')->name('admin');
    Route::get('admin/users', 'AdminController@users')->name('admin.users');
    Route::get('admin/users/{id}/delete', 'UserController@destroy')->name('admin.user.delete');
    Route::get('recipe/{id}/delete', 'RecipeController@destroy')->name('recipe.delete');
});

// User Profile
Route::get('profile/{id?}', 'ProfileController@index')->name('profile');


// Exports
Route::get('recipes/{id}/pdf', 'RecipeController@exportPDF')->name('recipePDF');
Route::get('search/recipes', array('uses' => 'RecipeController@search'));

web-3/resources/views/includes/messages.blade.php
@if(count($errors) > 0)
    @foreach($errors->all() as $error)
    <div class="alert alert-danger">
        {{$error}}
    </div>
    @endforeach
@endif

@if(session('success'))
    <div class="alert alert-success">
        {{session('success')}}
    </div>
@endif

@if(session('error'))
    <div class="alert alert-danger">
        {{session('error')}}
    </div>
@endif

web-3/resources/views/includes/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-dark bg-dark navbar-laravel">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('home') }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('recipes.index') }}">Recipes</a>
                </li>
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                    </li>
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" style="position:relative; padding-left:50px;" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            <img style="width:32px; height:32px; position:absolute; top:5px; left:8px; border-radius:50%; border: solid #fff9ea 0.2px;" src="{{ asset('uploads/avatars/' . Auth::User()->avatar) }}" alt="{{ Auth::User()->name }}'s Profile Picture.">        
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('profile', Auth::id()) }}">
                                My Profile
                            </a>
                            @can('isAdmin')
                                <a class="dropdown-item" href="{{ route('export') }}">
                                    User Export
                                </a>
                                <a class="dropdown-item" href="{{ route('admin') }}">
                                    Admin Panel
                                </a>
                            @endcan
                            <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>