web-3/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Home
Route::get('/', 'RecipeController@home')->name('home');

// Recipes
Route::resource('recipes', 'RecipeController');

Auth::routes();

// All those that require authentication.
Route::middleware(['auth'])->group(function() {
    Route::get('profile/{id}/edit', 'ProfileController@edit')->name('profile.edit');
    Route::put('profile/{id}/update', 'ProfileController@update')->name('profile.update');
    Route::get('profile/{id}/generate-token', 'ProfileController@generateToken')->name('profile.generate');
    Route::get('users/export/export-all', 'UserController@export_users')->name('user.export');
    Route::get('users/export', 'UserController@export')->name('export');
    Route::get('admin', 'AdminController@index')->name('admin');
    Route::get('admin/users', 'AdminController@users')->name('admin.users');
    Route::get('admin/users/{id}/delete', 'UserController@destroy')->name('admin.user.delete');
    Route::get('recipe/{id}/delete', 'RecipeController@destroy')->name('recipe.delete');
});

// User Profile
Route::get('profile/{id?}', 'ProfileController@index')->name('profile');


// Exports
Route::get('recipes/{id}/pdf', 'RecipeController@exportPDF')->name('recipePDF');
Route::get('search/recipes', array('uses' => 'RecipeController@search'));

web-3/resources/views/ProfileController/not-public.blade.php
@extends('layouts.app')

@section('title') 
    Not public
@endsection

@section('pageScript', asset('js/user-profile.js'))

@section('pageStyling', asset('css/profile.css'))

@section('content')
<div class="row">
    <div class="col">
        Unfortunately the profile you try to view is not public!
    </div>
</div>
@endsection

web-3/resources/views/ProfileController/profile-edit.blade.php
@extends('ProfileController.profile')

@section('user-data')
    {!! Form::open(['action' => ['ProfileController@update', $data['user']->id], 'method' => 'POST', 'files' => true]) !!}
        <div class="form-group">
            {{ Form::label('name', 'Name') }}
            {{ Form::text('name', $data['user']->name, ['class' => 'form-control', 'placeholder' => 'Your name']) }}
        </div>
        <div class="form-group">
            {{ Form::label('is_public', 'Public profile:') }}
            @if($data['user']->is_public == 0)
                {{ Form::checkbox('is_public', 'value') }}
            @else
                {{ Form::checkbox('is_public', 'value', true) }}
            @endif
        </div>
        <div class="form-group">
            {{ Form::label('avatar', 'Profile Picture') }}
            {{ Form::file('avatar') }}
        </div>
        {{ Form::hidden('_method', 'PUT') }}
        {{ Form::submit('Update Details', ['class' => 'btn btn-primary btn-sm']) }}
        <a href="{{ route('profile', $data['user']->id) }}" class="btn btn-danger btn-sm" >Cancel</a>
    {!! Form::close() !!}
@endsection

web-3/resources/views/ProfileController/profile-normal.blade.php
@extends('ProfileController.profile')

@section('user-data')
<table>
    <thead>
        <tr>
            <th></th>
            <th>Data</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Name: </td>
            <td>{{ $data['user']->name }}</td>
        </tr>
        <tr>
            <td>Public profile: </td>
            <td>
                @if( $data['user']->is_public == 0)
                    No
                @else
                    Yes
                @endif
            </td>
        </tr>
        @can('profile-owner', $data['user']->id)
            <tr>
                <td>
                    API Token
                </td>
                <td>
                    @if ($data['user']->api_token === null)
                        <a href="{{ route('profile.generate', $data['user']->id) }}" class="btn btn-secondary btn-sm">Generate</a>
                    @else
                        <button id="show-token-button" class="btn btn-danger btn-sm">Show</button>
                    @endif 
                </td>
            </tr>
            <tr>
                <td></td>
                <td id="api-td"></td>
            </tr>
            <script>
                (() => {
                    var btn = document.querySelector("#show-token-button");
                    var td = document.querySelector("#api-td");
                    btn.addEventListener("click", () => {
                        if (btn.innerHTML == "Show") {
                            td.innerHTML = "{{ $data['user']->api_token }}";
                            btn.innerHTML = "Hide";
                        } else {
                            td.innerHTML = "";
                            btn.innerHTML = "Show";
                        }
                        
                    })
                })();

            </script>
        @endcan
    </tbody>
</table>
{{-- Button should only be visible by the owner. --}}
@can('profile-owner', $data['user']->id)
    <a class="btn btn-secondary btn-sm" href="{{ route('profile.edit', $data['user']->id) }}">Change Details</a>
@endcan
@endsection

web-3/resources/views/ProfileController/profile.blade.php
@extends('layouts.app')

@section('title') 
  Profile of {{ $data['user']->name }}
@endsection

@section('pageScript', asset('js/user-profile.js'))

@section('pageStyling', asset('css/profile.css'))

@section('content')
  <div class="row">
    <div class="col">
      <div id="user">
        <h1>{{ $data['user']->name }}</h1>
        <img id="profilePicture" src="{{ asset('uploads/avatars/' . $data['user']->avatar) }}" alt="{{ $data['user']->name }}'s Profile Picture." class="img-thumbnail">
      </div>
    </div>
    <div class="col">
      <div id="user-data">
        @yield('user-data')
      </div>
      <div id="button-div">
        
      </div>
    </div>
    <div class="col">
      <div>
        <div class="stats">
          <div class="stat-label">
            Currently shared: 
          </div>
          <div class="stat-container">
          @if ($data['recipeCount'] == 1)
            {{ $data['recipeCount'] }} recipe
          @else
            {{ $data['recipeCount'] }} recipes
          @endif
          </div>
          <div class="stat-label">
              Last Time Shared: 
          </div>
          <div class="stat-container">
            @if($data['lastShared'] !== null)
              {{ $data['lastShared'] }}
            @else
              <b>Never</b>
            @endif
          </div>
        </div>
      </div>
    </div> 
  </div>
  <div id="recipeRow" class="row">
    <div class="col">
      @if ($data['recipeCount'] > 0 )
        <h1 id="recipeHeader">Shared Recipes</h1>
        <table id="recipe-table" class="table table-dark">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Title</th>
              <th scope="col">Created At</th>
              <th scope="col">Updated At</th>
            </tr>
          </thead>
          <tbody>
              @foreach ($data['userRecipes'] as $userRecipe)
              <tr onclick="location.href='{{ route('recipes.show', $userRecipe->id) }}'" class="recipe-row">
                <td height="15%" width="15%">
                    <img id="{{ asset('storage/cover_images/' . $userRecipe->cover_image_pixel) }}" src="{{ asset('storage/cover_images/' . $userRecipe->cover_image) }}" onmouseenter="change(this)" onmouseleave="change(this)" class="img-thumbnail rounded" >
                   <!-- <img src="{{ $userRecipe->image }}" style="height: 100px" class="img-thumbnail rounded"> -->
                </td>
                <td>{{ $userRecipe->title }}</td>
                <td>{{ $userRecipe->created_at->format('Y-m-d') }}</td>
                <td>{{ $userRecipe->updated_at->format('Y-m-d') }}</td>
                {{-- These buttons should only be visible by the user itself. --}}
                @can('profile-owner', $data['user']->id)
                  <td>
                    <div class="row">
                      <a href="{{ route('recipes.edit', $userRecipe->id) }}" class="btn btn-primary" >Edit</a>
                      {!!Form::open(['action' => ['RecipeController@destroy', $userRecipe->id], 'method' => 'POST', 'class' => 'pull-right'])!!}
                      {{Form::hidden('_method', 'DELETE')}}
                      {{Form::submit('Delete', ['class' => 'btn btn-danger'])}}
                      {!!Form::close()!!}
                      <a href="{{ route('recipePDF', $userRecipe->id) }}" class="btn btn-light" >PDF</a>
                    </div>
                  </td>
                @endcan
              </tr>
              @endforeach
          </tbody>
        </table>
        {{ $data['userRecipes']->links() }}
      @else
        <div>
          <h1>
            No recipes are shared!
          </h1>
        </div>
      @endif
      {{-- This button should be only available to the user self. --}}
      @can('profile-owner', $data['user']->id)
        <a href="{{ route('recipes.create') }}" class="btn btn-secondary">Share a Recipe</a>
      @endcan
    </div>
</div>
<script>
var normalImageTemp;
    function change(image){   
        if(!image.src.includes("NoImage.jpg")){    
            if(image.src.includes(image.id)){
                console.log("normal");
                image.src = normalImageTemp;
                normalImageTemp = "";
            }
            else{
                console.log("pixel");
                normalImageTemp = image.src;
                image.src = image.id;
            }
        }
    }
</script>
@endsection